# https://taskfile.dev

version: '3'

vars:
  target: pico2-w
  stacksize: 8kb
  DIRS: helloworld blinky blinky-pico-w external-button scan-i2c ssd1306 bme68x ds3231 ds3231-ntp logs #ntp-client

# example: task build-helloworld
# example: task flash-blinky
tasks:

  modinit:
    cmds:
      - for: {var: DIRS}
        cmd: cd {{.ITEM}} && go mod init {{.ITEM}} 
 
  tidy:
    cmds:
      - for: {var: DIRS}
        cmd: cd {{.ITEM}} && go mod tidy

  build-*:
    sources:
      - ./{{.ARG}}/main.go
    generates:
      - ./{{.ARG}}/flash.uf2
    vars:
      ARG: '{{index .MATCH 0}}'
    cmds:
      - cd {{.ARG}}
      - tinygo build -o ./{{.ARG}}/flash.uf2 -target={{.target}} -stack-size={{.stacksize}}  ./{{.ARG}}/main.go

  buildall:
    sources:
          - ./*/main.go
    generates:
          - ./*/flash.uf2
    cmds:
      - for: {var: DIRS}      
        cmd: tinygo build -o ./{{.ITEM}}/flash.uf2 -target={{.target}} -size short -stack-size={{.stacksize}} -monitor  ./{{.ITEM}}/main.go

  flash-*:
    vars:
      ARG: '{{index .MATCH 0}}'
    cmds:
      - tinygo flash -target={{.target}} -size short -stack-size={{.stacksize}} -monitor  ./{{.ARG}}/

  flashall:
    cmds:
      - for: {var: DIRS}
        cmd: tinygo flash -target={{.target}} -size short -stack-size={{.stacksize}} -monitor  ./{{.ITEM}}/

  clean:
    cmds:
      - for: {var: DIRS}
        cmd: rm -f ./{{.ITEM}}/*.uf2